config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :cars do
   member do
          put "like"=>"cars#upvote"
    put "unlike"=>"cars#downvote"
    end 
       member do
         get 'clone'
    end
 end
 root 'cars#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/azzet.rb
class Azzet < ActiveRecord::Base
  belongs_to :car
 has_attached_file :inage, styles: {medium: "640x480>", thumb: "200x200>"},
  default_url:  "/inages/:style/missing.png"
 validates_attachment_content_type :inage, content_type: /\Aimage\/.*\Z/
end

app/models/car.rb
class Car < ActiveRecord::Base
attr_accessible :marka, :model, :opis, :rocznik, :cena, :image,:azzets_attributes,:inage,:telefon
  has_many :azzets
  accepts_nested_attributes_for :azzets, :allow_destroy =>true
 acts_as_votable
 mount_uploader:image,ImageUploader 
def self.search(search)
           if search
             where (["marka LIKE ?","%#{search}%"])
            else 
             all
           end
       end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :clone, :upvote, :downvote]
  before_action :authenticate_admin!, only: [ :edit, :update, :destroy]
  # GET /cars
  # GET /cars.json
  def index
    @q = Car.ransack(params[:q])
    @cars = @q.result .search(params[:search]) .paginate(:page => params[:page], :per_page => 5)
    @q.build_sort if @q.sorts.empty?
  end
 def clone
  @car = Car.find(params[:id])
 end

  # GET /cars/1
  # GET /cars/1.json
  def show
   
   @w=0
   @t=0
  end

  # GET /cars/new
  def new
    @car = Car.new
    5.times { @car.azzets.build }
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
    5.times { @car.azzets.build }
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
 def update
    @car = Car.find(params[:id])
   
    if @car.update_attributes(params[:car])
      redirect_to @car, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def upvote 
   @car.upvote_from current_admin
   redirect_to cars_path
 end
 
 def downvote 
   @car.downvote_from current_admin
   redirect_to cars_path
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:marka, :model, :opis, :rocznik, :cena, :image,:inage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car, :html => { :multipart => true } do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marka %><br>
    <%= f.text_field :marka %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :opis %><br>
    <%= f.text_area :opis %>
  </div>
  <div class="field">
    <%= f.label :rocznik %><br>
    <%= f.text_field :rocznik %>
  </div>
  <div class="field">
    <%= f.label :cena %><br>
    <%= f.text_field :cena %>
  </div>
<div class="field">
    <%= f.label :telefon %><br>
    <%= f.text_field :telefon %>
  </div>
  <div class="field">
    <%= f.label :zdjecie_profilowe %><br>
    <%= f.file_field :image %>
  </div>
 <h4>galeria zdjec </h4>
 <%= f.fields_for :azzets do |azzet_fields| %>
<% if azzet_fields.object.new_record? %>
<p>
 <%= azzet_fields.file_field :inage %>
 </p>
<% end %>
<% end %>
<h4>galeria zdjec </h4> zaznacz zeby usunac <input type="checkbox" >
<%= f.fields_for  :azzets do |azzet_fields| %> 
  <% unless azzet_fields.object.new_record? %>
  <%= link_to image_tag(azzet_fields.object.inage.url(:thumb)),
             azzet_fields.object.inage.url(:original) %>
            <%= azzet_fields.check_box :_destroy  %>
 <%end%>
<%end%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/clone.html.erb
<h1>Clone</h1>
<%= form_for @car, url:'/cars',method: :post do |f| %>
 <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>
   
      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marka %><br>
    <%= f.text_field :marka %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :opis %><br>
    <%= f.text_area :opis %>
  </div>
  <div class="field">
    <%= f.label :rocznik %><br>
    <%= f.text_field :rocznik %>
  </div>
  <div class="field">
    <%= f.label :cena %><br>
    <%= f.text_field :cena %>
  </div>
  <div class="actions">
    <%= f.submit "zapisz" %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%=notice%></p>
<% if admin_signed_in? %>
 <h2><%= link_to "Nowe ogłoszenie",'/cars/new',class:'btn btn-succes' %></h2>
<%end%>
<font color="#9900cc"><center><h1>Samochody na sprzedaż</h1></center></font>
<br>
 

<%= search_form_for @q do |f| %>
  <div class="field">
    <h4><%= f.label :marka_cont, "Szukaj auta:" %>
    <%= f.text_field :marka_cont %>
    <%= f.label :cena_gteq, "Cena pomiedzy :" %>
    <%= f.text_field :cena_gteq %>
    <%= f.label :cena_lteq, "a :" %>
    <%= f.text_field :cena_lteq %>  
    
      Sortuj według:
  <%= f.sort_fields do |s| %>
    <%= s.sort_select %>
  <% end %>
  <%= f.submit "Search" %></h4>
  </div>
<br>
<br>

  
<% end %>


<% @cars.each do |car|%>


<div class="col-md-2">                                         
<%= image_tag car.image, class:"img-responsive"%>
 <div class="caption" style="text-align:center;">
 <%= link_to like_car_path(car), class:"like", method: :put do %>
   <button type="button" class="btn btn-info" aria-label="Left Align">
    <span  class="fa fa-thumbs-o-up tally-likes" style="color:green" aria-hidden="true"></span>
    <span class="badge"><%= car.get_upvotes.size %></span>
   </button>
 <%end%>
   <%= link_to unlike_car_path(car), class:"like", method: :put do %>
   <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="fa fa-thumbs-o-down tally-likes"style="color:red" aria-hidden="true" ></span>
    <span class="badge"><%= car.get_downvotes.size %></span>
   </button>
  
 <%end%>
<i class="fa fa-car" style="font-size:36px;color:#003333"></i>
</div>
</div>


<div class="col-md-10">
   <div class="col-md-12">
   <% if admin_signed_in? %>
  <%= link_to "Edytuj ogłoszenie","/cars/#{car.id}/edit",class:'btn btn-info btn-xs' %>
  <%= link_to "Usuń","/cars/#{car.id}",class:'btn btn-warning btn-xs', method: :delete, data:{confirm:'Are you sure?'} %>
  <%end%>
   <h4><%= link_to car.marka,car %></h4>
     </div>
   <div class="col-md-2">
    <strong><font color="#32CD99">Marka: </font></strong><font color="#3232CD"><%=car.marka%></font>
    </div>
    <div class="col-md-2">
    <strong><font color="#32CD99">model: </font></strong><font color="#3232CD"><%=car.model%></font>
    </div>
   <div class="col-md-2">
    <strong><font color="#32CD99">cena: </font></strong><font color="#3232CD"><%=car.cena%></font>
    </div>
   <div class="col-md-2">
    <strong><font color="#32CD99">rocznik: </font></strong><font color="#3232CD"><%=car.rocznik%></font>
    </div>
   <div class="col-md-4">
     <strong><font color="#32CD99">telefon:</font></strong><font color="#3232CD"><%=car.telefon%></font>
    </div>
   </div>
   <div class="col-md-12">
  <hr>
</div>
<% end %>

<div class="col-md-12">

<center><%= will_paginate @cars,renderer: BootstrapPagination::Rails %></center>
</div>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<%= form_for @car, :html => { :multipart => true }   do |f| %>
<div class="col-md-3">
<%= image_tag @car.image,size:"700", class:"img-responsive"%>
</div>
<div class="col-md-9">
 <div class="col-md-12"> 
 <h4><%= @car.marka %></h4>
  <hr>
  </div>
 <div class="col-md-3">
   <strong>model</strong>
  <%=@car.model%>
  </div>
<div class="col-md-3">
   <strong>telefon</strong>
  <%=@car.telefon%>
  </div>
  <div class="col-md-6">
  <strong>cena</strong>
  <%=@car.cena%>
  </div>
   <div class="col-md-12">
   <hr>
   <strong>opis</strong>
  <%=simple_format @car.opis%>
 </div>
</div>
<br>
<div class="col-md-12">
<br>
 <h4>galeria miniatur </h4>
</div>
<br>

<%= f.fields_for  :azzets do |azzet_fields| %> 
  <% unless azzet_fields.object.new_record? %>
 
  <%= link_to image_tag(azzet_fields.object.inage.url(:thumb)) ,
             azzet_fields.object.inage.url(:original) %>

<%end%> 
<%end%>
<br>
<h3><strong> Galeria zdjec</strong> </h3>
<br>
<div style="background-color:black" >
  <div id='carousel-custom' class='carousel slide' data-ride='carousel'>
        <div class='carousel-outer'>
            <!-- Wrapper for slides -->
            <div class='carousel-inner'>
                <div class='item active'>
                    <%= image_tag @car.image, class:"img-responsive"%>
                </div>

      <%= f.fields_for  :azzets do |azzet_fields| %> 
        <% unless azzet_fields.object.new_record? %>
                <div class='item'>
                    <%= link_to image_tag(azzet_fields.object.inage.url(:medium)) %>
                </div>
                <%end%> 
                <%end%>
            </div>

            <!-- Controls -->
            <a class='left carousel-control' href='#carousel-custom' data-slide='prev'>
                <span class='glyphicon glyphicon-chevron-left'></span>
            </a>
            <a class='right carousel-control' href='#carousel-custom' data-slide='next'>
                <span class='glyphicon glyphicon-chevron-right'></span>
            </a>
        </div>

        <!-- Indicators -->
        <ol class='carousel-indicators'>
          <li data-target='#carousel-custom' data-slide-to='0' class='active'><%= image_tag @car.image,size:"160", class:"img-responsive"%></li>
   <%= f.fields_for  :azzets do |azzet_fields| %> 
        <% unless azzet_fields.object.new_record? %>
            <li data-target='#carousel-custom' data-slide-to='<%=@t+1%>'><%= link_to image_tag(azzet_fields.object.inage.url(:thumb)) %></li>
            <% @t=@t+1 %>
      <%end%> 
                <%end%>
        </ol>
    </div>
  </div>
    
    <script src='js/jquery-1.11.0.min.js'></script>
    <script src='bootstrap/js/bootstrap.min.js'></script>

<%end%>
<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
    <meta charset="UTF-8">
    
    <link href='bootstrap/css/bootstrap.min.css' rel='stylesheet' />
    <style type='text/css'>
        #carousel-custom {
            margin: 20px auto;
            width: 1100px;
        }
        #carousel-custom .carousel-indicators {
            margin: 10px 0 0;
            overflow: auto;
            position: static;
            text-align: left;
            white-space: nowrap;
            width: 100%;
        }
        #carousel-custom .carousel-indicators li {
            background-color: transparent;
            -webkit-border-radius: 0;
            border-radius: 0;
            display: inline-block;
            height: auto;
            margin: 0 !important;
            width: auto;
        }
        #carousel-custom .carousel-indicators li img {
            display: block;
        }
        #carousel-custom .carousel-outer {
            position: relative;
        }
    </style>


<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 170%;
      margin: auto;
  }
  </style>


  <title>Samochody na sprzedaż</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:#D7F7DD">
<nav  class="navbar navbar-inverse">
  <div  class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/cars">
        Samochody na sprzedaż
      </a>
    </div>
 <ul class="navbar navbar-nav navbar-right">
 <% if admin_signed_in? %>
  <font color="green"><h4><li><%= link_to "Wyloguj",destroy_admin_session_url,:method =>'delete' %></li></h4></font>
  <% else %>
<font color="green"><h4><li><%=link_to "Zaloguj", new_admin_session_url%></li></h4></font>
 <% end %>
</ul>
   </div>
 </nav>
<div class="container-fluid" >
  <div class="row">
   <div class="col-md-12">


<%=  yield %>
</div>
</div>
</div>
</body>
</html>